# How to run on localhost: ansible-playbook --connection=local --inventory 127.0.0.1, install-jenkins.yaml
# How to run on remote: ansible-playbook -i 75.101.180.155, install-jenkins.yaml --user ec2-user --private-key ~/.ssh/dc-beleo.pem
# Ref: https://scriptcrunch.com/check-application-status-using-ansible/
# Ref: https://installvirtual.com/slack-notifications-ansible/
---
- hosts: all
  become: true

  tasks:
    - name: install wget
      yum:
        name: wget
        state: present
    - name: install openjdk
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: download jenkins.repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: import jenkins key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: install jenkins
      yum:
        name: jenkins
        state: present

    - name: start jenkins
      shell: /etc/init.d/jenkins start
      register: output

    - name: sleep for 30 seconds and continue with play
      wait_for: timeout=30
    
    - name: "wait for website to come up"
      uri:
        url: "http://localhost:8080/login"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 2
      delay: 5

    - name: Find my public ip
      uri: 
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response

    - name: send a message to chat in playbook
      telegram:
        token: '888266392:AAFVdjG093G_5tjwkczVL4je_uSPtkvxnRY'
        chat_id: 264827442
        msg: "Status of jenkins on host {{ ip_response.content }} is {{ output.stdout_lines }}"

    - name: Send notification to Slack
      slack:
        token: 'xoxp/585234658052-586340947575/595650069028/49b732547347eeb6585a03f360d8e86f'
        channel: "#monitoring"
        msg: "Status of jenkins on host {{ inventory_hostname }} is {{ output.stdout_lines }}"
      #delegate_to: localhost

    - name: init password jenkin
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: print init password jenkins
      debug:
        var: result.stdout
